#!/bin/bash

if (source venv/bin/activate) ; then
    source venv/bin/activate
    echo "Venv Activated..."
else 
    python -m venv venv 
    source venv/bin/activate
    pip install -r requirements.txt
    cd ..
    echo "Venv Activated..."
fi

python3 clear.py